import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <nav className="navbar navbar-expand-sm navbar-dark bg-white shadow-sm">
              <a className="navbar-brand" href="#">Navbar</a>
              <button className="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                  aria-expanded="false" aria-label="Toggle navigation"></button>
              <div className="collapse navbar-collapse" id="collapsibleNavId">
                  <ul className="navbar-nav me-auto mt-2 mt-lg-0 text-secondary">
                      <li className="nav-item">
                          <a className="nav-link active fw-bold text-secondary" href="#" aria-current="page">DAO <span className="visually-hidden">(current)</span></a>
                      </li>
                  </ul>
                  <form className="d-flex my-2 my-lg-0 px-2">
                      <button className="btn btn-outline-success my-2 my-sm-0" type="submit">connect wallet</button>
                  </form>
              </div>
          </nav>
          <div className='container mt-5'>
            <div className='row justify-content-center align-items-center'>
              <div className='col col-md-3'>
                  <p>Opened Proposals : </p>
              </div>
              <div className='col col-md-3'>
                  DAO Available Balance : 
              </div>
              <div className='col col-md-3'>
                  Personal Contributions :
              </div>
              <div className='col col-md-3'>
                Status : stakeholder
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
